# Generated by Django 4.0.2 on 2022-02-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripduration', models.IntegerField()),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('stoptime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
