# Generated by Django 4.0.2 on 2022-02-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_duration', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('stop_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_station_id', models.IntegerField(blank=True, null=True)),
                ('start_station_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_station_latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('start_station_longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('end_station_id', models.IntegerField(blank=True, null=True)),
                ('end_station_name', models.CharField(blank=True, max_length=100, null=True)),
                ('end_station_latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('end_station_longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('bikeid', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[(0, 'unknown'), (1, 'male'), (2, 'Female')], max_length=1, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('Subscriber', 'Annual Member'), ('Customer', '24-hour pass or 3-day pass user')], max_length=50, null=True)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
