# Generated by Django 4.0.2 on 2022-02-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeTrip',
            fields=[
                ('bikeid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rideable_type', models.CharField(blank=True, max_length=50, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('start_station_id', models.CharField(blank=True, max_length=50, null=True)),
                ('start_station_name', models.CharField(blank=True, max_length=100, null=True)),
                ('end_station_id', models.CharField(blank=True, max_length=50, null=True)),
                ('end_station_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_lat', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('start_lon', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('end_lon', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('member_casual', models.CharField(blank=True, choices=[('casual', 'casual'), ('Customer', 'member')], max_length=50, null=True)),
            ],
        ),
    ]
