# Generated by Django 4.0.2 on 2022-02-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nyc_Bike_Trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biketrip',
            name='gender',
            field=models.CharField(blank=True, choices=[(0, 'unknown'), (1, 'male'), (2, 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='biketrip',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Subscriber', 'Annual Member'), ('Customer', '24-hour pass or 3-day pass user')], max_length=50, null=True),
        ),
    ]
