# Generated by Django 4.0.2 on 2022-02-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nyc_Bike_Trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biketrip',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biketrip',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
