# Generated by Django 4.0.2 on 2022-02-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nyc_Bike_Trip', '0002_alter_biketrip_gender_alter_biketrip_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biketrip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
